const LOG_LTE_ML1_MAC_RAR_MSG1_REPORT: u16 = 0x167; // 0xB167 LTE MAC RAR (Msg1) Report
const LOG_LTE_ML1_MAC_RAR_MSG2_REPORT: u16 = 0x168; // 0xB168 LTE MAC RAR (Msg2) Report
const LOG_LTE_ML1_MAC_UE_IDENTIFICATION_MESSAGE_MSG3_REPORT: u16 = 0x169; // 0xB169 LTE MAC RAR (Msg3) Report
const LOG_LTE_ML1_MAC_CONTENTION_RESOLUTION_MESSAGE_MSG4_REPORT: u16 = 0x16A; // 0xB16A LTE MAC RAR (Msg4) Report
const LOG_LTE_ML1_CONNECTED_MODE_INTRA_FREQ_MEAS: u16 = 0x179; // 0xB179 LTE ML1 Connected Mode LTE Intra-Freq Measurements
const LOG_LTE_ML1_SERVING_CELL_MEAS_AND_EVAL: u16 = 0x17f; // 0xB17F LTE ML1 Serving Cell Meas and Eval
const LOG_LTE_ML1_NEIGHBOR_MEASUREMENTS: u16 = 0x180; // 0xB180 LTE ML1 Neighbor Measurements
const LOG_LTE_ML1_INTRA_FREQ_CELL_RESELECTION: u16 = 0x181; // 0xB181 LTE ML1 Intra Frequency Cell Reselection
const LOG_LTE_ML1_NEIGHBOR_CELL_MEAS_REQ_RESPONSE: u16 = 0x192; // B192 LTE ML1 Neighbor Cell Meas Request/Response
const LOG_LTE_ML1_SERVING_CELL_MEAS_RESPONSE: u16 = 0x193; // 0xB193 LTE ML1 Serving Cell Meas Response
const LOG_LTE_ML1_SEARCH_REQ_RESPONSE: u16 = 0x194; // 0xB194 LTE ML1 Search Request/Response
const LOG_LTE_ML1_CONNECTED_MODE_NEIGHBOR_MEAS_REQ_RESPONSE: u16 = 0x195; // 0xB195 LTE ML1 Connected Neighbor Meas Request/Response
const LOG_LTE_ML1_SERVING_CELL_INFO: u16 = 0x197; // 0xB197 LTE ML1 Serving Cell Information

// MAC
const LOG_LTE_MAC_RACH_TRIGGER: u16 = 0x61; // 0xB061 LTE MAC RACH Trigger
const LOG_LTE_MAC_RACH_RESPONSE: u16 = 0x62; // 0xB062 LTE MAC Rach Attempt
const LOG_LTE_MAC_DL_TRANSPORT_BLOCK: u16 = 0x63; // 0xB063 LTE MAC DL Transport Block
const LOG_LTE_MAC_UL_TRANSPORT_BLOCK: u16 = 0x64; // 0xB064 LTE MAC UL Transport Block

// PDCP
const LOG_LTE_PDCP_DL_CONFIG: u16 = 0xa0; // 0xB0A0 LTE PDCP DL Config
const LOG_LTE_PDCP_UL_CONFIG: u16 = 0xb0; // 0xB0B0 LTE PDCP UL Config
const LOG_LTE_PDCP_DL_DATA_PDU: u16 = 0xa1; // 0xB0A1 LTE PDCP DL Data PDU
const LOG_LTE_PDCP_UL_DATA_PDU: u16 = 0xb1; // 0xB0B1 LTE PDCP UL Data PDU
const LOG_LTE_PDCP_DL_CONTROL_PDU: u16 = 0xa2; // 0xB0A2 LTE PDCP DL Ctrl PDU
const LOG_LTE_PDCP_UL_CONTROL_PDU: u16 = 0xb2; // 0xB0B2 LTE PDCP UL Ctrl PDU
const LOG_LTE_PDCP_DL_CIPHER_DATA_PDU: u16 = 0xa3; // 0xB0A3 LTE PDCP DL Cipher Data PDU
const LOG_LTE_PDCP_UL_CIPHER_DATA_PDU: u16 = 0xb3; // 0xB0B3 LTE PDCP UL Cipher Data PDU
const LOG_LTE_PDCP_DL_SRB_INTEGRITY_DATA_PDU: u16 = 0xa5; // 0xB0A5 LTE PDCP DL SRB Integrity Data PDU
const LOG_LTE_PDCP_UL_SRB_INTEGRITY_DATA_PDU: u16 = 0xb5; // 0xB0B5 LTE PDCP UL SRB Integrity Data PDU

// RRC
const LOG_LTE_RRC_OTA_MESSAGE: u16 = 0xc0; // 0xB0C0 LTE RRC OTA Packet
const LOG_LTE_RRC_MIB_MESSAGE: u16 = 0xc1; // 0xB0C1 LTE RRC MIB Message Log Packet
const LOG_LTE_RRC_SERVING_CELL_INFO: u16 = 0xc2; // 0xB0C2 LTE RRC Serving Cell Info Log Pkt
const LOG_LTE_RRC_SUPPORTED_CA_COMBOS: u16 = 0xcd; // 0xB0CD LTE RRC Supported CA Combos

// NAS
const LOG_LTE_NAS_ESM_SEC_OTA_INCOMING_MESSAGE: u16 = 0xe0; // 0xB0E0 LTE NAS EMM Security Protected Incoming Msg
const LOG_LTE_NAS_ESM_SEC_OTA_OUTGOING_MESSAGE: u16 = 0xe1; // 0xB0E1 LTE NAS EMM Security Protected Outgoing Msg
const LOG_LTE_NAS_ESM_PLAIN_OTA_INCOMING_MESSAGE: u16 = 0xe2; // 0xB0E2 LTE NAS EMM Plain OTA Incoming Message
const LOG_LTE_NAS_ESM_PLAIN_OTA_OUTGOING_MESSAGE: u16 = 0xe3; // 0xB0E3 LTE NAS EMM Plain OTA Outgoing Message
const LOG_LTE_NAS_EMM_SEC_OTA_INCOMING_MESSAGE: u16 = 0xea; // 0xB0EA LTE NAS EMM Security Protected Incoming Msg
const LOG_LTE_NAS_EMM_SEC_OTA_OUTGOING_MESSAGE: u16 = 0xeb; // 0xB0EB LTE NAS EMM Security Protected Outgoing Msg
const LOG_LTE_NAS_EMM_PLAIN_OTA_INCOMING_MESSAGE: u16 = 0xec; // 0xB0EC LTE NAS EMM Plain OTA Incoming Message
const LOG_LTE_NAS_EMM_PLAIN_OTA_OUTGOING_MESSAGE: u16 = 0xed; // 0xB0ED LTE NAS EMM Plain OTA Outgoing Message